---
title: 'Local Agency 7 Participation Report'
output:
  distill::distill_article:
    toc:false:
      theme: theme.css
favicon: "images/favicon.ico"
github-repo: childpovertyactionlab/wic-participation-reports
---

## LA7 Participation Summary

```{r, include=FALSE}
#library(data.table)
library(tidyverse)
library(rio)
#library(ggthemes)
#library(directlabels)
library(leaflet)
library(sf)
library(plotly)
library(tigris)
library(reactable)
library(tigris)
library(CPALtools)
library(googlesheets4)
library(lubridate)

WIC_Participation <- import("data/WIC Participation Texas Average.csv") %>%
  mutate(Fiscal_Month = factor(Month,
                               levels = c(10:12, 1:9),
                               labels = c(month.abb[10:12], month.abb[1:9])))

WIC_LA7 <- WIC_Participation %>%
  filter(Project == 7 & Year >= 2020)

la7participation <- import("data/LA7 Monthly Clinic Participation Report Long.csv") %>%
  janitor::clean_names() %>%
  rename(clinic_no = site) %>%
  mutate(ClinicNo = as.character(clinic_no),
         date = as.Date(date, "%m/%d/%Y")) %>%
  select(-clinic_no) %>%
  filter(date >= as.Date("2020-01-01"))

la7partNewest <- la7participation %>%
  filter(date == max(date))

dallas_sf <- st_read("data/Dallas County Boundary.geojson") %>%
  st_transform(crs = 4326)

wic_eligible_sf <- st_read("data/WIC Eligibility by Tract North Texas.geojson") %>%
  st_transform(crs = 4326)

wic_eligDallas_sf <- st_read("data/WIC Eligibility by Tract Dallas County.geojson") %>%
  st_transform(crs = 4326)

LastYear <- la7participation %>%
  filter(date == ymd(max(date))-years(1)) %>%
  select(-date) %>% 
  rename(LastYear = participation)

sumOld <- sum(LastYear$LastYear, na.rm = TRUE)

ThisMonth <- la7participation %>%
  filter(date == ymd(max(date))) %>%
  select(-date) %>% 
  rename(ThisMonth = participation)

sumNew <- sum(ThisMonth$ThisMonth, na.rm = TRUE)

LastMonth <- la7participation %>%
  filter(date == ymd(max(date))-months(1))  %>%
  select(-date) %>% 
  rename(LastMonth = participation)

sumLast <- sum(LastMonth$LastMonth, na.rm = TRUE)

clinics <- read_sheet(ss = "https://docs.google.com/spreadsheets/d/16Wf9AYXo-_RNyaQp9owWnWf4tzC2sdzezjsu0DqD9uQ", sheet = "LA7 Clinics") %>%
  filter(Status == "ACTIVE") %>%
  st_as_sf(coords = c(x = "lon", y = "lat"), crs = 4269) %>%
    mutate(ClinicNo = as.character(ClinicNo)) %>%
  st_transform(crs = 4326)

clinicbuffer <- clinics %>%
  st_buffer(., dist = 15840) %>%
  GeoIntersect(., wic_eligible_sf) %>%
  group_by(Name, ClinicNo, Rent, SqFt, Address, City, ZIP) %>%
  summarise(WIC_eligible = sum(wic_eligibleE*PerIntSm, na.rm = TRUE)) %>%
  ungroup() %>%
  st_transform(crs = 4326) %>%
  mutate(ClinicNo = as.character(ClinicNo)) %>%
  left_join(., la7partNewest) %>%
  mutate(EligPart = participation/WIC_eligible) %>%
  left_join(., ThisMonth) %>%
  left_join(., LastMonth) %>%
  left_join(., LastYear) %>%
  mutate(ThisMonth = ifelse(is.na(ThisMonth), 0, ThisMonth),
         #LastYear = ifelse(is.na(LastYear), 0, LastYear),
         LastMonth = ifelse(is.na(LastMonth), 0, LastMonth),
         perpart = round((ThisMonth/sumNew)*100, digits = 2),
         perchange = round((ThisMonth-LastYear)/sumOld*100, digits = 2),
         permonth = round((ThisMonth-LastMonth)/sumOld*100, digits = 2)) %>%
  st_drop_geometry(.)

clinicjoin <- clinics %>%
  select(-Address, -City, -ZIP, -Name, -SqFt, -Rent, -WIC_eligible) %>%
  left_join(., clinicbuffer)

#names(clinics)
wic_eligible_sf <- wic_eligible_sf %>%
  st_transform(crs = 4326)

month <- as.character(month(ymd(max(la7participation$date)), abbr = FALSE, label = TRUE))
year <- as.character(year(ymd(max(la7participation$date))))

highways <- st_read("C:/Users/micha/CPAL Dropbox/Data Library/NCTCOG/Highways_(2019).shp") %>%
#highways <- st_read("E:/CPAL Dropbox/Data Library/NCTCOG/Highways_(2019).shp") %>%
  st_transform(crs = 4326) %>%
  st_intersection(., dallas_sf)
```


```{r, fig.height=5, fig.width=7, fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, layout="l-body-outset"}
WICmonth <- WIC_Participation %>%
  filter(Project == 7) %>%
  filter(Year >= 2019) %>%
  ggplot(aes(x=Date, 
             y=Total_Participants, 
             )) +
  geom_line(color = "#008097", size = 1.5) +
  labs(title = "Local Agency 7 Participation",
       #subtitle = "Participation by Month",
       x = "",
       y = "") +
  scale_y_continuous(labels = scales::comma,
                     breaks = scales::breaks_width(2500),
                     limits = c(57500, 67500)) +
  scale_x_date(expand = expansion(mult = c(0.05, 0.1)),
               date_breaks = "1 year", date_minor_breaks = "6 months", date_labels = "%Y") +
  theme_cpal(base_size = 16) +
  theme(legend.text=element_text(size=12))

ggplotly(WICmonth, tooltip = c("Date", "Total_Participants")) %>%
  layout(legend = list(
    orientation = "h",
    y = -0.1,
    x = 0.2))
```

## Current Participation by Clinic {-}

```{r, fig.height=5, fig.width=7, echo=FALSE, message=FALSE, warning=FALSE, layout="l-body-outset"}
WIClocal <- clinicjoin %>%
  mutate(EligPart = round(EligPart, digits = 2)) %>%
  ggplot(aes(x = reorder(site_name, EligPart), 
             y = EligPart)) +
  coord_flip() +
  geom_bar(stat = "identity", fill = "#008097", color = "#008097") +
  labs(title = paste(month, year, "Participation"),
       subtitle = "Local Agency 7",
       x = "",
       y = "") +
  scale_y_continuous(labels = scales::percent) +
  theme_cpal(base_size = 16) +
  theme(legend.text=element_text(size=12))

ggplotly(WIClocal, tooltip = "EligPart")
```

## Clinic Map {-}
```{r, fig.height=7, fig.width=7, echo=FALSE, message=FALSE, warning=FALSE, layout="l-body-outset"}

bins <- BAMMtools::getJenksBreaks(wic_eligDallas_sf$wic_eligibleE, k = 6)
pal <- colorBin("BuPu", domain = wic_eligDallas_sf$wic_eligibleE, bins = bins)

leaflet() %>%
  setView(lng = -96.7970, lat = 32.7767, zoom = 10) %>%
  addTiles(urlTemplate = cpal_mapbox, attribution = cpal_leaflet) %>%
  addPolygons(data = wic_eligDallas_sf,
              fillOpacity = 0.8,
              fillColor = ~pal(wic_eligibleE),
              color = "#FFFFFF",
              weight = 1) %>%
  addPolygons(data = highways,
              fillOpacity = 0,
              weight = 1,
              opacity = 0.8,
              color = "#595959") %>%
    addPolygons(data = dallas_sf,
              fillOpacity = 0,
              weight = 5,
              opacity = 1,
              color = "#595959") %>%
  addCircleMarkers(data = clinicjoin,
                   stroke = FALSE,
                   fillOpacity = 0.9,
                   fillColor = "#008097",
                   popup = paste0("<b>", "Clinic: ", "</b>", clinicjoin$site_name, "<br>",
                                 "<b>", "Total Participation: ", "</b>", clinicjoin$ThisMonth, "<br>",
                                 "<b>", "Percent Participation: ", "</b>", clinicjoin$perpart, "%", "<br>",
                                 "<b>", "YtY Change: ", "</b>", clinicjoin$perchange, "%"))

```

```{r, echo=FALSE, results='asis', layout="l-body-outset"}
clinicjoin %>%
  st_drop_geometry(.) %>%
  select(site_name, ThisMonth, perchange, permonth, EligPart) %>%
  mutate(perchange = paste0(round(perchange*100, digits = 0), "%"),
         permonth = paste0(round(permonth*100, digits = 0), "%"),
         EligPart = paste0(round(EligPart*100, digits = 0), "%")) %>%
  reactable(., columns = list(
    site_name = colDef(
      name = "Clinic"),
    ThisMonth = colDef(
      name = paste(month, year, "Participation")),
    perchange = colDef(
      name = "Percent Change (Year)"),
    permonth = colDef(
      name = "Percent Change (Month)"),
    EligPart = colDef(
      name = "Eligible Participation (3-Mile)")),
    theme = reactableTheme(
      headerStyle = list(
        "&:hover[aria-sort]" = list(background = "hsl(0, 0%, 96%)"),
        "&[aria-sort='ascending'], &[aria-sort='descending']" = list(background = "hsl(0, 0%, 96%)"),
        borderColor = "#555"
        )
      )
    )
```
## LA7 Participation Over Time {-}

```{r, fig.height=5, fig.width=7, fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, layout="l-body-outset"}
WICyear <- WIC_Participation %>%
  filter(Project == 7) %>%
  mutate(Participants_Diff = Total_Participants - lag(Total_Participants, order_by = Date, n = 12),
         highlight = ifelse(Participants_Diff >= 0, "Gain", "Loss")) %>%
  ggplot(aes(x = as.Date(factor(Date)), 
             y = Participants_Diff,
             fill = highlight)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("#008097", "#ec008c")) +
  labs(title = "Year to Year WIC Participation Change",
       subtitle = "Local Agency 7",
       x = "",
       y = "") + #color = "Year"
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme_cpal(base_size = 16) +
  theme(legend.text=element_text(size=12),
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))


ggplotly(WICyear, tooltip = c("Participants_Diff")) %>%
  layout(legend = list(
    orientation = "h",
    y = -0.3,
    x = 0))
```

## WIC Participation Across Texas {-}

```{r, fig.height=5, fig.width=7, fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, layout="l-body-outset"}
WICurban <- WIC_Participation %>%
  mutate(highlight=ifelse(Project==7, "Dallas", 
                          ifelse(Project %in% c(17, 26, 48), "Houston",
                                 ifelse(Project == 1, "Austin", 
                                        ifelse(Project == 41, "San Antonio", 
                                               ifelse(Project == 54, "Ft. Worth", 
                                                      ifelse(Project == 0, "Texas", "Other"))))))) %>%
  filter(highlight != "Other") %>%
  group_by(Date, highlight) %>%
  mutate(Total_Participants = sum(Total_Participants)) %>%
  ggplot(aes(x=Date, y=Total_Participants, color = highlight, size = highlight)) +
  geom_line() +
  scale_color_manual(values = c("#008097", "#e98816", "#eaca2d", "#ea8b98", "#b4b4b4", "#9bd9e3")) +
  scale_size_manual(values = c(0.5, 1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5)) +
  labs(title = "WIC Participation in Texas Counties",
       subtitle = "Between October 2015 through February 2022",
       x = "",
       y = "") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(expand = expansion(mult = c(0.05, 0.1)),
               date_breaks = "1 year", date_labels = "%Y") +
  guides(size = FALSE, color = FALSE) +
  theme_cpal(base_size = 16) +
  theme(legend.text=element_text(size=12))

ggplotly(WICurban, tooltip = c("Total_Participants")) %>%
  layout(legend = list(
    orientation = "h",
    y = -0.3,
    x = 0))
```


