# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.

title: Census Tracts Comparison
description: >- # this means to ignore newlines until "baseurl:"
  Child Poverty Action Lab (CPAL)
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://childpovertyactionlab.github.io"

theme: jekyll-theme-slate
#remote_theme: jekyll/minima

disqus:
  shortname: CPAL

#links_to_prev_next: true

#minima:
#  skin: classic
  # skin: dark
  # skin: solarized-dark
#  date_format: "%a, %b %-d, %Y (week %V)"
#  social_links:
#    twitter: na
#    github: na
    # linkedin: na
    # facebook: na

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-pwa-plugin

tagline: CPAL Repo

feed:
  posts_limit: 100

#author:
#  name: na
#  email: na

#logo: /assets/corsego-saas-tree-logo.png

#permalink: "/:title"

#google_analytics: na

#jekyll_admin:
#  hidden_links:
#    - posts
#    - pages
#    - staticfiles
#    - datafiles
#    - configuration

# SEO tag useful info
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
